export const CHANGE_INFO = 'CHANGE_INFO';
export const CHANGE_UTILITY = 'CHANGE_UTILITY';
export const CHANGE_HEALTH_MANA = 'CHANGE_HEALTH_MANA';
export const CHANGE_STAT = 'CHANGE_STAT';
export const HANGE_WEAPONS_GROUP = 'CHANGE_WEAPONS_GROUP';
