const infoActionTypes = {
  CHANGE_GENDER: 'CHANGE_GENDER',
  CHANGE_AGE: 'CHANGE_AGE',
  CHANGE_NAME: 'CHANGE_NAME',
  CHANGE_CLASS: 'CHANGE_CLASS',
  CHANGE_RACE: 'CHANGE_RACE',
  CHANGE_LEVEL: 'CHANGE_LEVEL',
  CHANGE_XP: 'CHANGE_XP',
  CHANGE_BACKGROUND: 'CHANGE_BACKGROUND'
};

const utilityActionTypes = {
  CHANGE_DEFENSE: 'CHANGE_DEFENSE',
  CHANGE_ARMOR: 'CHANGE_ARMOR',
  CHANGE_SPEED: 'CHANGE_SPEED',
  CHANGE_AP: 'CHANGE_AP'
};

const healthActionTypes = {
  CHANGE_MAX_HEALTH: 'CHANGE_MAX_HEALTH',
  CHANGE_CURRENT_HEALTH: 'CHANGE_CURRENT_HEALTH',
  CHANGE_ADJUST_HEALTH: 'CHANGE_ADJUST_HEALTH',
  CHANGE_MAX_MANA: 'CHANGE_MAX_MANA',
  CHANGE_CURRENT_MANA: 'CHANGE_CURRENT_MANA',
  CHANGE_ADJUST_MANA: 'CHANGE_ADJUST_MANA'
};

const statsActionTypes = {
  CHANGE_FOCUS: 'CHANGE_FOCUS',
  CHANGE_PRIMARY_STATS: 'CHANGE_PRIMARY_STATS',
  CHANGE_STAT_VALUE: 'CHANGE_STAT_VALUE'
};

export const types = {
  infoActionTypes,
  utilityActionTypes,
  healthActionTypes,
  statsActionTypes
};
